# Generated by Django 4.0.2 on 2022-02-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listauction',
            name='item_condition',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used'), ('R', 'Refurbished')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='listauction',
            name='shipping_options',
            field=models.CharField(choices=[('Gr', 'Ground'), ('Exp', 'Express'), ('Pr', 'Priority'), ('Int', 'International')], default='Gr', max_length=3),
        ),
    ]
