# Generated by Django 4.0.2 on 2022-02-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
