# Generated by Django 4.0.2 on 2022-02-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listauction_item_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listauction',
            name='item_condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Refurbished', 'Refurbished')], default='New', max_length=30),
        ),
        migrations.AlterField(
            model_name='listauction',
            name='shipping_options',
            field=models.CharField(choices=[('Ground', 'Ground'), ('Express', 'Express'), ('Priority', 'Priority'), ('International', 'International')], default='Ground', max_length=30),
        ),
    ]
