# Generated by Django 4.0.2 on 2022-02-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listauction_item_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listauction',
            name='shipping_options',
        ),
    ]
