# Generated by Django 4.0.2 on 2022-02-28 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listauction_shipping_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categorylist',
            field=models.ManyToManyField(related_name='auction_categories', to='auctions.ListAuction'),
        ),
        migrations.RemoveField(
            model_name='listauction',
            name='categories',
        ),
        migrations.AddField(
            model_name='listauction',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='auctions.category'),
        ),
    ]
