# Generated by Django 4.0.2 on 2022-03-03 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category_categorylist_remove_listauction_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listauction',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
