# Generated by Django 4.0.2 on 2022-02-25 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_auctionlisting_item_condition_user_auctionlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_image', models.ImageField(upload_to='./static/auctions/auction_images')),
                ('item_name', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=500000)),
                ('shipping_options', models.CharField(choices=[('N', 'New'), ('U', 'Used'), ('R', 'Refurbished')], default='Gr', max_length=3)),
                ('item_condition', models.CharField(choices=[('N', 'New'), ('U', 'Used'), ('R', 'Refurbished')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(choices=[('Brooms', 'Brooms'), ('Wands', 'Wands'), ('Capes', 'Capes')], default='Brooms', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ListAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_to_list', to='auctions.auctionitem')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='categories',
            field=models.ManyToManyField(to='auctions.Category'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_item', to='auctions.auctionitem'),
        ),
        migrations.AlterField(
            model_name='user',
            name='auctionlist',
            field=models.ManyToManyField(related_name='auctions', to='auctions.ListAuction'),
        ),
        migrations.DeleteModel(
            name='AuctionListing',
        ),
    ]
