# Generated by Django 4.0.2 on 2022-03-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listauction_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='listauction',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
