# Generated by Django 4.0.2 on 2022-03-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listauction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='high_bidder',
            field=models.BooleanField(default=True),
        ),
    ]
