# Generated by Django 4.0.2 on 2022-02-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionitem_category_listauction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='shipping_options',
            field=models.CharField(choices=[('Gr', 'Ground'), ('Exp', 'Express'), ('Pr', 'Priority'), ('Int', 'International')], default='Gr', max_length=3),
        ),
    ]
