# Generated by Django 4.0.2 on 2022-03-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_bid_high_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='listauction',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
