# Generated by Django 4.0.2 on 2022-02-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionitem_shipping_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='listing_image',
            field=models.ImageField(upload_to='auction_images'),
        ),
    ]
