# Generated by Django 4.0.2 on 2022-03-04 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listauction_current_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listauction',
            name='current_bid',
        ),
    ]
