# Generated by Django 4.0.2 on 2022-03-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='bids',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to='auctions.bid'),
        ),
    ]
