# Generated by Django 4.0.2 on 2022-03-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_rename_conmment_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(null=True),
        ),
    ]
