# Generated by Django 4.0.2 on 2022-03-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_user_avatar_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
