# Generated by Django 4.0.2 on 2022-03-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_category_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categorylist',
            field=models.ManyToManyField(related_name='categorylist', to='auctions.ListAuction'),
        ),
    ]
