# Generated by Django 4.0.2 on 2022-03-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_category_categorylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categorylist',
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
