# Generated by Django 4.0.2 on 2022-03-06 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_remove_category_categorylist_alter_category_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listauction',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='listauction',
            name='listing_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
